// Comprehensive location data for astrology and birth chart applications

export interface Country {
  code: string;
  name: string;
  timezone: string;
  flag: string;
}

export interface LocationData {
  countries: Country[];
  cities: Record<string, string[]>;
}

export const countries: Country[] = [
  { code: 'AD', name: 'Andorra', timezone: 'Europe/Andorra', flag: '🇦🇩' },
  { code: 'AE', name: 'United Arab Emirates', timezone: 'Asia/Dubai', flag: '🇦🇪' },
  { code: 'AF', name: 'Afghanistan', timezone: 'Asia/Kabul', flag: '🇦🇫' },
  { code: 'AG', name: 'Antigua and Barbuda', timezone: 'America/Antigü', flag: '🇦🇬' },
  { code: 'AI', name: 'Anguilla', timezone: 'America/Anguilla', flag: '🇦🇮' },
  { code: 'AL', name: 'Albania', timezone: 'Europe/Tirane', flag: '🇦🇱' },
  { code: 'AM', name: 'Armenia', timezone: 'Asia/Yerevan', flag: '🇦🇲' },
  { code: 'AO', name: 'Angola', timezone: 'Africa/Luanda', flag: '🇦🇴' },
  { code: 'AQ', name: 'Antarctica', timezone: 'Antarctica/Palmer', flag: '🇦🇶' },
  { code: 'AR', name: 'Argentina', timezone: 'America/Argentina/Buenos_Aires', flag: '🇦🇷' },
  { code: 'AS', name: 'American Samoa', timezone: 'Pacific/Pago_Pago', flag: '🇦🇸' },
  { code: 'AT', name: 'Austria', timezone: 'Europe/Vienna', flag: '🇦🇹' },
  { code: 'AU', name: 'Australia', timezone: 'Australia/Sydney', flag: '🇦🇺' },
  { code: 'AW', name: 'Aruba', timezone: 'America/Aruba', flag: '🇦🇼' },
  { code: 'AX', name: 'Åland Islands', timezone: 'Europe/Mariehamn', flag: '🇦🇽' },
  { code: 'AZ', name: 'Azerbaijan', timezone: 'Asia/Baku', flag: '🇦🇿' },
  { code: 'BA', name: 'Bosnia and Herzegovina', timezone: 'Europe/Sarajevo', flag: '🇧🇦' },
  { code: 'BB', name: 'Barbados', timezone: 'America/Barbados', flag: '🇧🇧' },
  { code: 'BD', name: 'Bangladesh', timezone: 'Asia/Dhaka', flag: '🇧🇩' },
  { code: 'BE', name: 'Belgium', timezone: 'Europe/Brussels', flag: '🇧🇪' },
  { code: 'BF', name: 'Burkina Faso', timezone: 'Africa/Ouagadougou', flag: '🇧🇫' },
  { code: 'BG', name: 'Bulgaria', timezone: 'Europe/Sofia', flag: '🇧🇬' },
  { code: 'BH', name: 'Bahrain', timezone: 'Asia/Bahrain', flag: '🇧🇭' },
  { code: 'BI', name: 'Burundi', timezone: 'Africa/Bujumbura', flag: '🇧🇮' },
  { code: 'BJ', name: 'Benin', timezone: 'Africa/Porto-Novo', flag: '🇧🇯' },
  { code: 'BL', name: 'Saint Barthélemy', timezone: 'America/St_Barthelemy', flag: '🇧🇱' },
  { code: 'BM', name: 'Bermuda', timezone: 'Atlantic/Bermuda', flag: '🇧🇲' },
  { code: 'BN', name: 'Brunei', timezone: 'Asia/Brunei', flag: '🇧🇳' },
  { code: 'BO', name: 'Bolivia', timezone: 'America/La_Paz', flag: '🇧🇴' },
  { code: 'BQ', name: 'Caribbean Netherlands', timezone: 'America/Kralendijk', flag: '🇧🇶' },
  { code: 'BR', name: 'Brazil', timezone: 'America/Sao_Paulo', flag: '🇧🇷' },
  { code: 'BS', name: 'Bahamas', timezone: 'America/Nassau', flag: '🇧🇸' },
  { code: 'BT', name: 'Bhutan', timezone: 'Asia/Thimphu', flag: '🇧🇹' },
  { code: 'BV', name: 'Bouvet Island', timezone: 'Europe/Oslo', flag: '🇧🇻' },
  { code: 'BW', name: 'Botswana', timezone: 'Africa/Gaborone', flag: '🇧🇼' },
  { code: 'BY', name: 'Belarus', timezone: 'Europe/Minsk', flag: '🇧🇾' },
  { code: 'BZ', name: 'Belize', timezone: 'America/Belize', flag: '🇧🇿' },
  { code: 'CA', name: 'Canada', timezone: 'America/Toronto', flag: '🇨🇦' },
  { code: 'CC', name: 'Cocos Islands', timezone: 'Indian/Cocos', flag: '🇨🇨' },
  { code: 'CD', name: 'Democratic Republic of the Congo', timezone: 'Africa/Kinshasa', flag: '🇨🇩' },
  { code: 'CF', name: 'Central African Republic', timezone: 'Africa/Bangui', flag: '🇨🇫' },
  { code: 'CG', name: 'Republic of the Congo', timezone: 'Africa/Brazzaville', flag: '🇨🇬' },
  { code: 'CH', name: 'Switzerland', timezone: 'Europe/Zurich', flag: '🇨🇭' },
  { code: 'CI', name: 'Côte d\'Ivoire', timezone: 'Africa/Abidjan', flag: '🇨🇮' },
  { code: 'CK', name: 'Cook Islands', timezone: 'Pacific/Rarotonga', flag: '🇨🇰' },
  { code: 'CL', name: 'Chile', timezone: 'America/Santiago', flag: '🇨🇱' },
  { code: 'CM', name: 'Cameroon', timezone: 'Africa/Douala', flag: '🇨🇲' },
  { code: 'CN', name: 'China', timezone: 'Asia/Shanghai', flag: '🇨🇳' },
  { code: 'CO', name: 'Colombia', timezone: 'America/Bogota', flag: '🇨🇴' },
  { code: 'CR', name: 'Costa Rica', timezone: 'America/Costa_Rica', flag: '🇨🇷' },
  { code: 'CU', name: 'Cuba', timezone: 'America/Havana', flag: '🇨🇺' },
  { code: 'CV', name: 'Cape Verde', timezone: 'Atlantic/Cape_Verde', flag: '🇨🇻' },
  { code: 'CW', name: 'Curaçao', timezone: 'America/Curacao', flag: '🇨🇼' },
  { code: 'CX', name: 'Christmas Island', timezone: 'Indian/Christmas', flag: '🇨🇽' },
  { code: 'CY', name: 'Cyprus', timezone: 'Asia/Nicosia', flag: '🇨🇾' },
  { code: 'CZ', name: 'Czech Republic', timezone: 'Europe/Prague', flag: '🇨🇿' },
  { code: 'DE', name: 'Germany', timezone: 'Europe/Berlin', flag: '🇩🇪' },
  { code: 'DJ', name: 'Djibouti', timezone: 'Africa/Djibouti', flag: '🇩🇯' },
  { code: 'DK', name: 'Denmark', timezone: 'Europe/Copenhagen', flag: '🇩🇰' },
  { code: 'DM', name: 'Dominica', timezone: 'America/Dominica', flag: '🇩🇲' },
  { code: 'DO', name: 'Dominican Republic', timezone: 'America/Santo_Domingo', flag: '🇩🇴' },
  { code: 'DZ', name: 'Algeria', timezone: 'Africa/Algiers', flag: '🇩🇿' },
  { code: 'EC', name: 'Ecuador', timezone: 'America/Guayaquil', flag: '🇪🇨' },
  { code: 'EE', name: 'Estonia', timezone: 'Europe/Tallinn', flag: '🇪🇪' },
  { code: 'EG', name: 'Egypt', timezone: 'Africa/Cairo', flag: '🇪🇬' },
  { code: 'EH', name: 'Western Sahara', timezone: 'Africa/El_Aaiun', flag: '🇪🇭' },
  { code: 'ER', name: 'Eritrea', timezone: 'Africa/Asmara', flag: '🇪🇷' },
  { code: 'ES', name: 'Spain', timezone: 'Europe/Madrid', flag: '🇪🇸' },
  { code: 'ET', name: 'Ethiopia', timezone: 'Africa/Addis_Ababa', flag: '🇪🇹' },
  { code: 'FI', name: 'Finland', timezone: 'Europe/Helsinki', flag: '🇫🇮' },
  { code: 'FJ', name: 'Fiji', timezone: 'Pacific/Fiji', flag: '🇫🇯' },
  { code: 'FK', name: 'Falkland Islands', timezone: 'Atlantic/Stanley', flag: '🇫🇰' },
  { code: 'FM', name: 'Micronesia', timezone: 'Pacific/Chuuk', flag: '🇫🇲' },
  { code: 'FO', name: 'Faroe Islands', timezone: 'Atlantic/Faroe', flag: '🇫🇴' },
  { code: 'FR', name: 'France', timezone: 'Europe/Paris', flag: '🇫🇷' },
  { code: 'GA', name: 'Gabon', timezone: 'Africa/Libreville', flag: '🇬🇦' },
  { code: 'GB', name: 'United Kingdom', timezone: 'Europe/London', flag: '🇬🇧' },
  { code: 'GD', name: 'Grenada', timezone: 'America/Grenada', flag: '🇬🇩' },
  { code: 'GE', name: 'Georgia', timezone: 'Asia/Tbilisi', flag: '🇬🇪' },
  { code: 'GF', name: 'French Guiana', timezone: 'America/Cayenne', flag: '🇬🇫' },
  { code: 'GG', name: 'Guernsey', timezone: 'Europe/Guernsey', flag: '🇬🇬' },
  { code: 'GH', name: 'Ghana', timezone: 'Africa/Accra', flag: '🇬🇭' },
  { code: 'GI', name: 'Gibraltar', timezone: 'Europe/Gibraltar', flag: '🇬🇮' },
  { code: 'GL', name: 'Greenland', timezone: 'America/Godthab', flag: '🇬🇱' },
  { code: 'GM', name: 'Gambia', timezone: 'Africa/Banjul', flag: '🇬🇲' },
  { code: 'GN', name: 'Guinea', timezone: 'Africa/Conakry', flag: '🇬🇳' },
  { code: 'GP', name: 'Guadeloupe', timezone: 'America/Guadeloupe', flag: '🇬🇵' },
  { code: 'GQ', name: 'Equatorial Guinea', timezone: 'Africa/Malabo', flag: '🇬🇶' },
  { code: 'GR', name: 'Greece', timezone: 'Europe/Athens', flag: '🇬🇷' },
  { code: 'GS', name: 'South Georgia', timezone: 'Atlantic/South_Georgia', flag: '🇬🇸' },
  { code: 'GT', name: 'Guatemala', timezone: 'America/Guatemala', flag: '🇬🇹' },
  { code: 'GU', name: 'Guam', timezone: 'Pacific/Guam', flag: '🇬🇺' },
  { code: 'GW', name: 'Guinea-Bissau', timezone: 'Africa/Bissau', flag: '🇬🇼' },
  { code: 'GY', name: 'Guyana', timezone: 'America/Guyana', flag: '🇬🇾' },
  { code: 'HK', name: 'Hong Kong', timezone: 'Asia/Hong_Kong', flag: '🇭🇰' },
  { code: 'HM', name: 'Heard Island', timezone: 'Indian/Kerguelen', flag: '🇭🇲' },
  { code: 'HN', name: 'Honduras', timezone: 'America/Tegucigalpa', flag: '🇭🇳' },
  { code: 'HR', name: 'Croatia', timezone: 'Europe/Zagreb', flag: '🇭🇷' },
  { code: 'HT', name: 'Haiti', timezone: 'America/Port-au-Prince', flag: '🇭🇹' },
  { code: 'HU', name: 'Hungary', timezone: 'Europe/Budapest', flag: '🇭🇺' },
  { code: 'ID', name: 'Indonesia', timezone: 'Asia/Jakarta', flag: '🇮🇩' },
  { code: 'IE', name: 'Ireland', timezone: 'Europe/Dublin', flag: '🇮🇪' },
  { code: 'IL', name: 'Israel', timezone: 'Asia/Jerusalem', flag: '🇮🇱' },
  { code: 'IM', name: 'Isle of Man', timezone: 'Europe/Isle_of_Man', flag: '🇮🇲' },
  { code: 'IN', name: 'India', timezone: 'Asia/Kolkata', flag: '🇮🇳' },
  { code: 'IO', name: 'British Indian Ocean Territory', timezone: 'Indian/Chagos', flag: '🇮🇴' },
  { code: 'IQ', name: 'Iraq', timezone: 'Asia/Baghdad', flag: '🇮🇶' },
  { code: 'IR', name: 'Iran', timezone: 'Asia/Tehran', flag: '🇮🇷' },
  { code: 'IS', name: 'Iceland', timezone: 'Atlantic/Reykjavik', flag: '🇮🇸' },
  { code: 'IT', name: 'Italy', timezone: 'Europe/Rome', flag: '🇮🇹' },
  { code: 'JE', name: 'Jersey', timezone: 'Europe/Jersey', flag: '🇯🇪' },
  { code: 'JM', name: 'Jamaica', timezone: 'America/Jamaica', flag: '🇯🇲' },
  { code: 'JO', name: 'Jordan', timezone: 'Asia/Amman', flag: '🇯🇴' },
  { code: 'JP', name: 'Japan', timezone: 'Asia/Tokyo', flag: '🇯🇵' },
  { code: 'KE', name: 'Kenya', timezone: 'Africa/Nairobi', flag: '🇰🇪' },
  { code: 'KG', name: 'Kyrgyzstan', timezone: 'Asia/Bishkek', flag: '🇰🇬' },
  { code: 'KH', name: 'Cambodia', timezone: 'Asia/Phnom_Penh', flag: '🇰🇭' },
  { code: 'KI', name: 'Kiribati', timezone: 'Pacific/Tarawa', flag: '🇰🇮' },
  { code: 'KM', name: 'Comoros', timezone: 'Indian/Comoro', flag: '🇰🇲' },
  { code: 'KN', name: 'Saint Kitts and Nevis', timezone: 'America/St_Kitts', flag: '🇰🇳' },
  { code: 'KP', name: 'North Korea', timezone: 'Asia/Pyongyang', flag: '🇰🇵' },
  { code: 'KR', name: 'South Korea', timezone: 'Asia/Seoul', flag: '🇰🇷' },
  { code: 'KW', name: 'Kuwait', timezone: 'Asia/Kuwait', flag: '🇰🇼' },
  { code: 'KY', name: 'Cayman Islands', timezone: 'America/Cayman', flag: '🇰🇾' },
  { code: 'KZ', name: 'Kazakhstan', timezone: 'Asia/Almaty', flag: '🇰🇿' },
  { code: 'LA', name: 'Laos', timezone: 'Asia/Vientiane', flag: '🇱🇦' },
  { code: 'LB', name: 'Lebanon', timezone: 'Asia/Beirut', flag: '🇱🇧' },
  { code: 'LC', name: 'Saint Lucia', timezone: 'America/St_Lucia', flag: '🇱🇨' },
  { code: 'LI', name: 'Liechtenstein', timezone: 'Europe/Vaduz', flag: '🇱🇮' },
  { code: 'LK', name: 'Sri Lanka', timezone: 'Asia/Colombo', flag: '🇱🇰' },
  { code: 'LR', name: 'Liberia', timezone: 'Africa/Monrovia', flag: '🇱🇷' },
  { code: 'LS', name: 'Lesotho', timezone: 'Africa/Maseru', flag: '🇱🇸' },
  { code: 'LT', name: 'Lithuania', timezone: 'Europe/Vilnius', flag: '🇱🇹' },
  { code: 'LU', name: 'Luxembourg', timezone: 'Europe/Luxembourg', flag: '🇱🇺' },
  { code: 'LV', name: 'Latvia', timezone: 'Europe/Riga', flag: '🇱🇻' },
  { code: 'LY', name: 'Libya', timezone: 'Africa/Tripoli', flag: '🇱🇾' },
  { code: 'MA', name: 'Morocco', timezone: 'Africa/Casablanca', flag: '🇲🇦' },
  { code: 'MC', name: 'Monaco', timezone: 'Europe/Monaco', flag: '🇲🇨' },
  { code: 'MD', name: 'Moldova', timezone: 'Europe/Chisinau', flag: '🇲🇩' },
  { code: 'ME', name: 'Montenegro', timezone: 'Europe/Podgorica', flag: '🇲🇪' },
  { code: 'MF', name: 'Saint Martin', timezone: 'America/Marigot', flag: '🇲🇫' },
  { code: 'MG', name: 'Madagascar', timezone: 'Indian/Antananarivo', flag: '🇲🇬' },
  { code: 'MH', name: 'Marshall Islands', timezone: 'Pacific/Majuro', flag: '🇲🇭' },
  { code: 'MK', name: 'North Macedonia', timezone: 'Europe/Skopje', flag: '🇲🇰' },
  { code: 'ML', name: 'Mali', timezone: 'Africa/Bamako', flag: '🇲🇱' },
  { code: 'MM', name: 'Myanmar', timezone: 'Asia/Rangoon', flag: '🇲🇲' },
  { code: 'MN', name: 'Mongolia', timezone: 'Asia/Ulaanbaatar', flag: '🇲🇳' },
  { code: 'MO', name: 'Macao', timezone: 'Asia/Macau', flag: '🇲🇴' },
  { code: 'MP', name: 'Northern Mariana Islands', timezone: 'Pacific/Saipan', flag: '🇲🇵' },
  { code: 'MQ', name: 'Martinique', timezone: 'America/Martinique', flag: '🇲🇶' },
  { code: 'MR', name: 'Mauritania', timezone: 'Africa/Nouakchott', flag: '🇲🇷' },
  { code: 'MS', name: 'Montserrat', timezone: 'America/Montserrat', flag: '🇲🇸' },
  { code: 'MT', name: 'Malta', timezone: 'Europe/Malta', flag: '🇲🇹' },
  { code: 'MU', name: 'Mauritius', timezone: 'Indian/Mauritius', flag: '🇲🇺' },
  { code: 'MV', name: 'Maldives', timezone: 'Indian/Maldives', flag: '🇲🇻' },
  { code: 'MW', name: 'Malawi', timezone: 'Africa/Blantyre', flag: '🇲🇼' },
  { code: 'MX', name: 'Mexico', timezone: 'America/Mexico_City', flag: '🇲🇽' },
  { code: 'MY', name: 'Malaysia', timezone: 'Asia/Kuala_Lumpur', flag: '🇲🇾' },
  { code: 'MZ', name: 'Mozambique', timezone: 'Africa/Maputo', flag: '🇲🇿' },
  { code: 'NA', name: 'Namibia', timezone: 'Africa/Windhoek', flag: '🇳🇦' },
  { code: 'NC', name: 'New Caledonia', timezone: 'Pacific/Noumea', flag: '🇳🇨' },
  { code: 'NE', name: 'Niger', timezone: 'Africa/Niamey', flag: '🇳🇪' },
  { code: 'NF', name: 'Norfolk Island', timezone: 'Pacific/Norfolk', flag: '🇳🇫' },
  { code: 'NG', name: 'Nigeria', timezone: 'Africa/Lagos', flag: '🇳🇬' },
  { code: 'NI', name: 'Nicaragua', timezone: 'America/Managua', flag: '🇳🇮' },
  { code: 'NL', name: 'Netherlands', timezone: 'Europe/Amsterdam', flag: '🇳🇱' },
  { code: 'NO', name: 'Norway', timezone: 'Europe/Oslo', flag: '🇳🇴' },
  { code: 'NP', name: 'Nepal', timezone: 'Asia/Kathmandu', flag: '🇳🇵' },
  { code: 'NR', name: 'Nauru', timezone: 'Pacific/Nauru', flag: '🇳🇷' },
  { code: 'NU', name: 'Niue', timezone: 'Pacific/Niue', flag: '🇳🇺' },
  { code: 'NZ', name: 'New Zealand', timezone: 'Pacific/Auckland', flag: '🇳🇿' },
  { code: 'OM', name: 'Oman', timezone: 'Asia/Muscat', flag: '🇴🇲' },
  { code: 'PA', name: 'Panama', timezone: 'America/Panama', flag: '🇵🇦' },
  { code: 'PE', name: 'Peru', timezone: 'America/Lima', flag: '🇵🇪' },
  { code: 'PF', name: 'French Polynesia', timezone: 'Pacific/Tahiti', flag: '🇵🇫' },
  { code: 'PG', name: 'Papua New Guinea', timezone: 'Pacific/Port_Moresby', flag: '🇵🇬' },
  { code: 'PH', name: 'Philippines', timezone: 'Asia/Manila', flag: '🇵🇭' },
  { code: 'PK', name: 'Pakistan', timezone: 'Asia/Karachi', flag: '🇵🇰' },
  { code: 'PL', name: 'Poland', timezone: 'Europe/Warsaw', flag: '🇵🇱' },
  { code: 'PM', name: 'Saint Pierre and Miquelon', timezone: 'America/Miquelon', flag: '🇵🇲' },
  { code: 'PN', name: 'Pitcairn Islands', timezone: 'Pacific/Pitcairn', flag: '🇵🇳' },
  { code: 'PR', name: 'Puerto Rico', timezone: 'America/Puerto_Rico', flag: '🇵🇷' },
  { code: 'PS', name: 'Palestine', timezone: 'Asia/Gaza', flag: '🇵🇸' },
  { code: 'PT', name: 'Portugal', timezone: 'Europe/Lisbon', flag: '🇵🇹' },
  { code: 'PW', name: 'Palau', timezone: 'Pacific/Palau', flag: '🇵🇼' },
  { code: 'PY', name: 'Paraguay', timezone: 'America/Asuncion', flag: '🇵🇾' },
  { code: 'QA', name: 'Qatar', timezone: 'Asia/Qatar', flag: '🇶🇦' },
  { code: 'RE', name: 'Réunion', timezone: 'Indian/Reunion', flag: '🇷🇪' },
  { code: 'RO', name: 'Romania', timezone: 'Europe/Bucharest', flag: '🇷🇴' },
  { code: 'RS', name: 'Serbia', timezone: 'Europe/Belgrade', flag: '🇷🇸' },
  { code: 'RU', name: 'Russia', timezone: 'Europe/Moscow', flag: '🇷🇺' },
  { code: 'RW', name: 'Rwanda', timezone: 'Africa/Kigali', flag: '🇷🇼' },
  { code: 'SA', name: 'Saudi Arabia', timezone: 'Asia/Riyadh', flag: '🇸🇦' },
  { code: 'SB', name: 'Solomon Islands', timezone: 'Pacific/Guadalcanal', flag: '🇸🇧' },
  { code: 'SC', name: 'Seychelles', timezone: 'Indian/Mahe', flag: '🇸🇨' },
  { code: 'SD', name: 'Sudan', timezone: 'Africa/Khartoum', flag: '🇸🇩' },
  { code: 'SE', name: 'Sweden', timezone: 'Europe/Stockholm', flag: '🇸🇪' },
  { code: 'SG', name: 'Singapore', timezone: 'Asia/Singapore', flag: '🇸🇬' },
  { code: 'SH', name: 'Saint Helena', timezone: 'Atlantic/St_Helena', flag: '🇸🇭' },
  { code: 'SI', name: 'Slovenia', timezone: 'Europe/Ljubljana', flag: '🇸🇮' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', timezone: 'Arctic/Longyearbyen', flag: '🇸🇯' },
  { code: 'SK', name: 'Slovakia', timezone: 'Europe/Bratislava', flag: '🇸🇰' },
  { code: 'SL', name: 'Sierra Leone', timezone: 'Africa/Freetown', flag: '🇸🇱' },
  { code: 'SM', name: 'San Marino', timezone: 'Europe/San_Marino', flag: '🇸🇲' },
  { code: 'SN', name: 'Senegal', timezone: 'Africa/Dakar', flag: '🇸🇳' },
  { code: 'SO', name: 'Somalia', timezone: 'Africa/Mogadishu', flag: '🇸🇴' },
  { code: 'SR', name: 'Suriname', timezone: 'America/Paramaribo', flag: '🇸🇷' },
  { code: 'SS', name: 'South Sudan', timezone: 'Africa/Juba', flag: '🇸🇸' },
  { code: 'ST', name: 'São Tomé and Príncipe', timezone: 'Africa/Sao_Tome', flag: '🇸🇹' },
  { code: 'SV', name: 'El Salvador', timezone: 'America/El_Salvador', flag: '🇸🇻' },
  { code: 'SX', name: 'Sint Maarten', timezone: 'America/Lower_Princes', flag: '🇸🇽' },
  { code: 'SY', name: 'Syria', timezone: 'Asia/Damascus', flag: '🇸🇾' },
  { code: 'SZ', name: 'Eswatini', timezone: 'Africa/Mbabane', flag: '🇸🇿' },
  { code: 'TC', name: 'Turks and Caicos Islands', timezone: 'America/Grand_Turk', flag: '🇹🇨' },
  { code: 'TD', name: 'Chad', timezone: 'Africa/Ndjamena', flag: '🇹🇩' },
  { code: 'TF', name: 'French Southern Territories', timezone: 'Indian/Kerguelen', flag: '🇹🇫' },
  { code: 'TG', name: 'Togo', timezone: 'Africa/Lome', flag: '🇹🇬' },
  { code: 'TH', name: 'Thailand', timezone: 'Asia/Bangkok', flag: '🇹🇭' },
  { code: 'TJ', name: 'Tajikistan', timezone: 'Asia/Dushanbe', flag: '🇹🇯' },
  { code: 'TK', name: 'Tokelau', timezone: 'Pacific/Fakaofo', flag: '🇹🇰' },
  { code: 'TL', name: 'Timor-Leste', timezone: 'Asia/Dili', flag: '🇹🇱' },
  { code: 'TM', name: 'Turkmenistan', timezone: 'Asia/Ashgabat', flag: '🇹🇲' },
  { code: 'TN', name: 'Tunisia', timezone: 'Africa/Tunis', flag: '🇹🇳' },
  { code: 'TO', name: 'Tonga', timezone: 'Pacific/Tongatapu', flag: '🇹🇴' },
  { code: 'TR', name: 'Turkey', timezone: 'Europe/Istanbul', flag: '🇹🇷' },
  { code: 'TT', name: 'Trinidad and Tobago', timezone: 'America/Port_of_Spain', flag: '🇹🇹' },
  { code: 'TV', name: 'Tuvalu', timezone: 'Pacific/Funafuti', flag: '🇹🇻' },
  { code: 'TW', name: 'Taiwan', timezone: 'Asia/Taipei', flag: '🇹🇼' },
  { code: 'TZ', name: 'Tanzania', timezone: 'Africa/Dar_es_Salaam', flag: '🇹🇿' },
  { code: 'UA', name: 'Ukraine', timezone: 'Europe/Kiev', flag: '🇺🇦' },
  { code: 'UG', name: 'Uganda', timezone: 'Africa/Kampala', flag: '🇺🇬' },
  { code: 'UM', name: 'United States Minor Outlying Islands', timezone: 'Pacific/Wake', flag: '🇺🇲' },
  { code: 'US', name: 'United States', timezone: 'America/New_York', flag: '🇺🇸' },
  { code: 'UY', name: 'Uruguay', timezone: 'America/Montevideo', flag: '🇺🇾' },
  { code: 'UZ', name: 'Uzbekistan', timezone: 'Asia/Tashkent', flag: '🇺🇿' },
  { code: 'VA', name: 'Vatican City', timezone: 'Europe/Vatican', flag: '🇻🇦' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', timezone: 'America/St_Vincent', flag: '🇻🇨' },
  { code: 'VE', name: 'Venezuela', timezone: 'America/Caracas', flag: '🇻🇪' },
  { code: 'VG', name: 'British Virgin Islands', timezone: 'America/Tortola', flag: '🇻🇬' },
  { code: 'VI', name: 'United States Virgin Islands', timezone: 'America/St_Thomas', flag: '🇻🇮' },
  { code: 'VN', name: 'Vietnam', timezone: 'Asia/Ho_Chi_Minh', flag: '🇻🇳' },
  { code: 'VU', name: 'Vanuatu', timezone: 'Pacific/Efate', flag: '🇻🇺' },
  { code: 'WF', name: 'Wallis and Futuna', timezone: 'Pacific/Wallis', flag: '🇼🇫' },
  { code: 'WS', name: 'Samoa', timezone: 'Pacific/Apia', flag: '🇼🇸' },
  { code: 'YE', name: 'Yemen', timezone: 'Asia/Aden', flag: '🇾🇪' },
  { code: 'YT', name: 'Mayotte', timezone: 'Indian/Mayotte', flag: '🇾🇹' },
  { code: 'ZA', name: 'South Africa', timezone: 'Africa/Johannesburg', flag: '🇿🇦' },
  { code: 'ZM', name: 'Zambia', timezone: 'Africa/Lusaka', flag: '🇿🇲' },
  { code: 'ZW', name: 'Zimbabwe', timezone: 'Africa/Harare', flag: '🇿🇼' },
];

export const cities: Record<string, string[]> = {
  AD: ['Andorra la Vella', 'Canillo', 'Encamp', 'Escaldes-Engordany', "La Massana", 'Ordino', 'Sant Julià de Lòria'],
  AE: ['Dubai', 'Abu Dhabi', 'Sharjah', 'Al Ain', 'Ajman', 'Ras Al Khaimah', 'Fujairah', 'Umm Al Quwain'],
  AF: ['Kabul', 'Kandahar', 'Herat', 'Mazar-i-Sharif', 'Kunduz', 'Jalalabad', 'Lashkar Gah', 'Taloqan'],
  AG: ['Saint John\'s', 'All Saints', 'Liberta', 'Potter\'s Village', 'Bolans', 'Swetes', 'Codrington'],
  AI: ['The Valley', 'Blowing Point', 'Sandy Ground', 'East End', 'George Hill', 'Island Harbour'],
  AL: ['Tirana', 'Durrës', 'Vlorë', 'Elbasan', 'Shkodër', 'Fier', 'Korçë', 'Berat', 'Lushnjë', 'Kavajë'],
  AM: ['Yerevan', 'Gyumri', 'Vanadzor', 'Vagharshapat', 'Hrazdan', 'Abovyan', 'Kapan', 'Armavir'],
  AO: ['Luanda', 'Huambo', 'Lobito', 'Benguela', 'Kuito', 'Lubango', 'Malanje', 'Namibe', 'Soyo'],
  AQ: ['McMurdo Station', 'Rothera Research Station', 'Palmer Station', 'Belgrano II Base'],
  AR: ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'San Miguel de Tucumán', 'La Plata', 'Mar del Plata', 'Salta', 'Santa Fe', 'San Juan'],
  AS: ['Pago Pago', 'Tafuna', 'Leone', 'Faleniu', 'Mesepa', 'Ili\'ili', 'Taulaga'],
  AT: ['Vienna', 'Graz', 'Linz', 'Salzburg', 'Innsbruck', 'Klagenfurt', 'Villach', 'Wels', 'Sankt Pölten', 'Dornbirn'],
  AU: ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Gold Coast', 'Newcastle', 'Canberra', 'Sunshine Coast', 'Wollongong'],
  AW: ['Oranjestad', 'San Nicolaas', 'Noord', 'Santa Cruz', 'Paradera', 'Tanki Leendert'],
  AX: ['Mariehamn', 'Jomala', 'Finström', 'Lemland', 'Saltvik', 'Hammarland'],
  AZ: ['Baku', 'Ganja', 'Sumqayit', 'Mingachevir', 'Qabalá', 'Lankaran', 'Shaki', 'Yevlakh', 'Nakhchivan', 'Shirvan'],
  BA: ['Sarajevo', 'Banja Luka', 'Tuzla', 'Zenica', 'Mostar', 'Prijedor', 'Brčko', 'Bijeljina', 'Trebinje', 'Široki Brijeg'],
  BB: ['Bridgetown', 'Speightstown', 'Oistins', 'Bathsheba', 'Holetown', 'Crane', 'Six Cross Roads'],
  BD: ['Dhaka', 'Chittagong', 'Khulna', 'Rajshahi', 'Sylhet', 'Rangpur', 'Barisal', 'Mymensingh', 'Comilla', 'Narayanganj'],
  BE: ['Brussels', 'Antwerp', 'Ghent', 'Charleroi', 'Liège', 'Bruges', 'Namur', 'Leuven', 'Mons', 'Aalst'],
  BF: ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou', 'Banfora', 'Ouahigouya', 'Pouytenga', 'Kaya', 'Tenkodogo'],
  BG: ['Sofia', 'Plovdiv', 'Varna', 'Burgas', 'Ruse', 'Stara Zagora', 'Pleven', 'Sliven', 'Dobrich', 'Shumen'],
  BH: ['Manama', 'Riffa', 'Muharraq', 'Hamad Town', 'A\'ali', 'Isa Town', 'Sitra', 'Budaiya', 'Jidhafs'],
  BI: ['Bujumbura', 'Gitega', 'Muyinga', 'Ruyigi', 'Ngozi', 'Rutana', 'Kayanza', 'Bururi', 'Muramvya'],
  BJ: ['Porto-Novo', 'Cotonou', 'Parakou', 'Djougou', 'Bohicon', 'Kandi', 'Lokossa', 'Ouidah', 'Abomey'],
  BL: ['Gustavia', 'Lorient', 'Saint-Jean'],
  BM: ['Hamilton', 'Saint George', 'Somerset', 'Flatts'],
  BN: ['Bandar Seri Begawan', 'Kuala Belait', 'Seria', 'Tutong', 'Bangar', 'Jerudong'],
  BO: ['La Paz', 'Santa Cruz de la Sierra', 'Cochabamba', 'Sucre', 'Oruro', 'Tarija', 'Potosí', 'Cobija', 'Trinidad'],
  BQ: ['Kralendijk', 'The Bottom', 'Oranjestad'],
  BR: ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Manaus', 'Curitiba', 'Recife', 'Goiânia'],
  BS: ['Nassau', 'Lucaya', 'Freeport', 'West End', 'Coopers Town', 'Marsh Harbour', 'High Rock'],
  BT: ['Thimphu', 'Phuntsholing', 'Punakha', 'Wangdue', 'Samdrup Jongkhar', 'Trashigang', 'Mongar'],
  BV: ['Research Station'],
  BW: ['Gaborone', 'Francistown', 'Molepolole', 'Maun', 'Lobatse', 'Selibe Phikwe', 'Mahalapye', 'Kanye'],
  BY: ['Minsk', 'Gomel', 'Mogilev', 'Vitebsk', 'Grodno', 'Brest', 'Bobruisk', 'Baranovichi', 'Borisov', 'Pinsk'],
  BZ: ['Belize City', 'San Ignacio', 'Orange Walk', 'Belmopan', 'Dangriga', 'Corozal', 'Benque Viejo del Carmen'],
  CA: ['Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Edmonton', 'Ottawa', 'Winnipeg', 'Quebec City', 'Hamilton', 'Kitchener'],
  CC: ['West Island', 'Home Island', 'Direction Island', 'Horsburgh Island'],
  CD: ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kisangani', 'Masina', 'Kananga', 'Likasi', 'Kolwezi', 'Tshikapa'],
  CF: ['Bangui', 'Bimbo', 'Berbérati', 'Carnot', 'Bambari', 'Bouar', 'Bossangoa', 'Bria'],
  CG: ['Brazzaville', 'Pointe-Noire', 'Dolisie', 'Nkayi', 'Mossendjo', 'Owando', 'Ouesso', 'Madingou'],
  CH: ['Zurich', 'Geneva', 'Basel', 'Lausanne', 'Bern', 'Winterthur', 'Lucerne', 'St. Gallen', 'Lugano', 'Biel/Bienne'],
  CI: ['Abidjan', 'Bouaké', 'Daloa', 'Yamoussoukro', 'San-Pédro', 'Divo', 'Korhogo', 'Anyama', 'Gagnoa'],
  CK: ['Avarua', 'Amuri', 'Matavera', 'Arorangi', 'Titikaveka'],
  CL: ['Santiago', 'Valparaíso', 'Concepción', 'La Serena', 'Temuco', 'Iquique', 'Rancagua', 'Talca', 'Arica', 'Chillán'],
  CM: ['Douala', 'Yaoundé', 'Bamenda', 'Bafoussam', 'Garoua', 'Maroua', 'Nkongsamba', 'Loum', 'Kumba'],
  CN: ['Shanghai', 'Beijing', 'Guangzhou', 'Shenzhen', 'Tianjin', 'Wuhan', 'Dongguan', 'Chengdu', 'Nanjing', 'Xi\'an'],
  CO: ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena', 'Cúcuta', 'Soledad', 'Ibagué', 'Bucaramanga', 'Soacha'],
  CR: ['San José', 'Cartago', 'Puntarenas', 'Limón', 'Alajuela', 'Heredia', 'Desamparados', 'Paraíso'],
  CU: ['Havana', 'Santiago de Cuba', 'Camagüey', 'Holguín', 'Guantánamo', 'Santa Clara', 'Las Tunas', 'Bayamo', 'Cienfuegos'],
  CV: ['Praia', 'Mindelo', 'Santa Maria', 'Assomada', 'Porto Novo', 'Espargos', 'Ribeira Grande'],
  CW: ['Willemstad', 'Sint Michiel', 'Soto', 'Barber', 'Nieuw Nederland', 'Sint Joris'],
  CX: ['Flying Fish Cove', 'Silver City', 'Drumsite'],
  CY: ['Nicosia', 'Limassol', 'Larnaca', 'Famagusta', 'Paphos', 'Kyrenia', 'Morphou', 'Paralimni'],
  CZ: ['Prague', 'Brno', 'Ostrava', 'Plzen', 'Liberec', 'Olomouc', 'Budweis', 'Hradec Králové', 'Ústí nad Labem', 'Pardubice'],
  DE: ['Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt', 'Stuttgart', 'Düsseldorf', 'Dortmund', 'Essen', 'Leipzig'],
  DJ: ['Djibouti City', 'Ali Sabieh', 'Dikhil', 'Tadjoura', 'Obock', 'Arta'],
  DK: ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg', 'Esbjerg', 'Randers', 'Kolding', 'Horsens', 'Vejle', 'Roskilde'],
  DM: ['Roseau', 'Portsmouth', 'Marigot', 'Berekua', 'Mahaut', 'Saint Joseph', 'Wesley'],
  DO: ['Santo Domingo', 'Santiago', 'Santo Domingo Oeste', 'Santo Domingo Este', 'San Pedro de Macorís', 'La Romana', 'Bella Vista'],
  DZ: ['Algiers', 'Oran', 'Constantine', 'Batna', 'Djelfa', 'Sétif', 'Annaba', 'Sidi Bel Abbès', 'Biskra', 'Téebessa'],
  EC: ['Quito', 'Guayaquil', 'Cuenca', 'Santo Domingo', 'Machala', 'Durán', 'Manta', 'Portoviejo', 'Ambato', 'Riobamba'],
  EE: ['Tallinn', 'Tartu', 'Narva', 'Pärnu', 'Kohtla-Järve', 'Viljandi', 'Rakvere', 'Maardu', 'Sillamäe', 'Kuressaare'],
  EG: ['Cairo', 'Alexandria', 'Giza', 'Shubra El Kheima', 'Port Said', 'Suez', 'Luxor', 'Mansoura', 'El Mahalla El Kubra', 'Tanta'],
  EH: ['El Aaiún', 'Dakhla', 'Smara', 'Bojador', 'Güera'],
  ER: ['Asmara', 'Keren', 'Massawa', 'Assab', 'Mendefera', 'Barentu', 'Adi Keyh', 'Adi Quala'],
  ES: ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Zaragoza', 'Málaga', 'Murcia', 'Palma', 'Las Palmas', 'Bilbao'],
  ET: ['Addis Ababa', 'Dire Dawa', 'Mek\'ele', 'Adama', 'Awasa', 'Bahir Dar', 'Jimma', 'Jijiga', 'Shashamane', 'Nekemte'],
  FI: ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Oulu', 'Turku', 'Jyväskylä', 'Lahti', 'Kuopio', 'Pori'],
  FJ: ['Suva', 'Lautoka', 'Nadi', 'Labasa', 'Ba', 'Tavua', 'Sigatoka', 'Nausori', 'Savusavu'],
  FK: ['Stanley', 'Mount Pleasant', 'Goose Green', 'Darwin'],
  FM: ['Palikir', 'Weno', 'Tofol', 'Kolonia'],
  FO: ['Tórshavn', 'Klaksvík', 'Hoyvík', 'Argir', 'Vestmanna', 'Fuglafjørður'],
  FR: ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Montpellier', 'Bordeaux', 'Lille'],
  GA: ['Libreville', 'Port-Gentil', 'Franceville', 'Oyem', 'Moanda', 'Mouila', 'Lambaréné', 'Tchibanga'],
  GB: ['London', 'Birmingham', 'Manchester', 'Glasgow', 'Liverpool', 'Bristol', 'Sheffield', 'Leeds', 'Edinburgh', 'Cardiff'],
  GD: ['Saint George\'s', 'Gouyave', 'Grenville', 'Victoria', 'Saint David\'s'],
  GE: ['Tbilisi', 'Kutaisi', 'Batumi', 'Rustavi', 'Zugdidi', 'Gori', 'Poti', 'Kobuleti', 'Khashuri', 'Samtredia'],
  GF: ['Cayenne', 'Saint-Laurent-du-Maroni', 'Kourou', 'Maná', 'Saint-Georges', 'Maripasoula'],
  GG: ['Saint Peter Port', 'Saint Sampson', 'Vale', 'Castel', 'Saint Saviour'],
  GH: ['Accra', 'Kumasi', 'Tamale', 'Takoradi', 'Tema', 'Cape Coast', 'Sekondi', 'Obuasi', 'Madina', 'Koforidua'],
  GI: ['Gibraltar'],
  GL: ['Nuuk', 'Sisimiut', 'Ilulissat', 'Qaqortoq', 'Aasiaat', 'Maniitsoq', 'Tasiilaq'],
  GM: ['Banjul', 'Serekunda', 'Brikama', 'Bakau', 'Georgetown', 'Lamin', 'Gunjur'],
  GN: ['Conakry', 'Nzérékoré', 'Kankan', 'Kindia', 'Labe', 'Mamou', 'Boke', 'Siguiri'],
  GP: ['Basse-Terre', 'Pointe-à-Pitre', 'Abymes', 'Baie-Mahault', 'Le Gosier', 'Petit-Bourg'],
  GQ: ['Malabo', 'Bata', 'Ebebiyin', 'Aconibe', 'Añisoc', 'Luba', 'Evinayong'],
  GR: ['Athens', 'Thessaloniki', 'Patras', 'Piraeus', 'Larissa', 'Heraklion', 'Peristeri', 'Kallithea', 'Acharnes', 'Kalamaria'],
  GS: ['King Edward Point', 'Grytviken'],
  GT: ['Guatemala City', 'Villa Nueva', 'Petapa', 'San Juan Sacatepéquez', 'Quetzaltenango', 'Villa Canales', 'Escuintla'],
  GU: ['Hagåtña', 'Dededo', 'Yigo', 'Tamuning', 'Mangilao', 'Barrigada', 'Santa Rita'],
  GW: ['Bissau', 'Bafatá', 'Gabú', 'Bissorã', 'Bolama', 'Cacheu', 'Bubaque'],
  GY: ['Georgetown', 'Linden', 'New Amsterdam', 'Anna Regina', 'Bartica', 'Skeldon', 'Rosignol'],
  HK: ['Hong Kong', 'Kowloon', 'Tsuen Wan', 'Yuen Long', 'Tuen Mun', 'Tai Po', 'Sha Tin', 'Kwun Tong'],
  HM: ['Atlas Cove'],
  HN: ['Tegucigalpa', 'San Pedro Sula', 'Choloma', 'La Ceiba', 'El Progreso', 'Choluteca', 'Comayagua', 'Puerto Cortés'],
  HR: ['Zagreb', 'Split', 'Rijeka', 'Osijek', 'Zadar', 'Slavonski Brod', 'Pula', 'Sesvete', 'Karlovac', 'Varaždin'],
  HT: ['Port-au-Prince', 'Carrefour', 'Delmas', 'Cap-Haïtien', 'Pétion-Ville', 'Gonaïves', 'Saint-Marc', 'Les Cayes'],
  HU: ['Budapest', 'Debrecen', 'Szeged', 'Miskolc', 'Pécs', 'Győr', 'Nyíregyháza', 'Kecskemét', 'Székesfehérvár', 'Szombathely'],
  ID: ['Jakarta', 'Surabaya', 'Medan', 'Bekasi', 'Bandung', 'Depok', 'Tangerang', 'Palembang', 'Semarang', 'Makassar'],
  IE: ['Dublin', 'Cork', 'Limerick', 'Galway', 'Waterford', 'Drogheda', 'Dundalk', 'Swords', 'Bray', 'Navan'],
  IL: ['Jerusalem', 'Tel Aviv', 'Haifa', 'Rishon LeZion', 'Petah Tikva', 'Ashdod', 'Netanya', 'Beer Sheva', 'Holon', 'Bnei Brak'],
  IM: ['Douglas', 'Onchan', 'Ramsey', 'Peel', 'Port Erin', 'Castletown', 'Laxey'],
  IN: ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai', 'Kolkata', 'Pune', 'Ahmedabad', 'Jaipur', 'Surat'],
  IO: ['Diego Garcia'],
  IQ: ['Baghdad', 'Basra', 'Mosul', 'Erbil', 'Sulaymaniyah', 'Najaf', 'Karbala', 'Nasiriyah', 'Amarah', 'Diwaniyah'],
  IR: ['Tehran', 'Mashhad', 'Isfahan', 'Karaj', 'Shiraz', 'Tabriz', 'Qom', 'Ahvaz', 'Kermanshah', 'Urmia'],
  IS: ['Reykjavik', 'Kópavogur', 'Hafnarfjörður', 'Akureyri', 'Reykjanesbær', 'Garðabær', 'Mosfellsbær', 'Árborg'],
  IT: ['Rome', 'Milan', 'Naples', 'Turin', 'Palermo', 'Genoa', 'Bologna', 'Florence', 'Bari', 'Catania'],
  JE: ['Saint Helier', 'Saint Saviour', 'Saint Clement', 'Saint Lawrence', 'Saint Brelade'],
  JM: ['Kingston', 'Spanish Town', 'Portmore', 'Montego Bay', 'May Pen', 'Mandeville', 'Old Harbour', 'Savanna-la-Mar'],
  JO: ['Amman', 'Zarqa', 'Irbid', 'Russeifa', 'Wadi as-Sir', 'Ajloun', 'Madaba', 'Aqaba', 'Mafraq', 'Jerash'],
  JP: ['Tokyo', 'Yokohama', 'Osaka', 'Nagoya', 'Sapporo', 'Fukuoka', 'Kobe', 'Kawasaki', 'Kyoto', 'Saitama'],
  KE: ['Nairobi', 'Mombasa', 'Nakuru', 'Eldoret', 'Kisumu', 'Thika', 'Malindi', 'Kitale', 'Garissa', 'Kakamega'],
  KG: ['Bishkek', 'Osh', 'Jalal-Abad', 'Karakol', 'Tokmok', 'Uzgen', 'Naryn', 'Talas', 'Batken', 'Kant'],
  KH: ['Phnom Penh', 'Siem Reap', 'Battambang', 'Sihanoukville', 'Poipet', 'Kampong Cham', 'Pursat', 'Takéo'],
  KI: ['Tarawa', 'Betio', 'Bikenibeu', 'Teaoraereke'],
  KM: ['Moroni', 'Mutsamudu', 'Fomboni', 'Domoni', 'Sima'],
  KN: ['Basseterre', 'Charlestown', 'Sandy Point Town', 'Cayon', 'Dieppe Bay Town'],
  KP: ['Pyongyang', 'Hamhung', 'Chongjin', 'Nampo', 'Wonsan', 'Sinuiju', 'Tanchon', 'Kaechon'],
  KR: ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Suwon', 'Ulsan', 'Changwon', 'Goyang'],
  KW: ['Kuwait City', 'Al Ahmadi', 'Hawally', 'As Salimiyah', 'Sabah as Salim', 'Al Farwaniyah'],
  KY: ['George Town', 'West Bay', 'Bodden Town', 'East End', 'North Side'],
  KZ: ['Almaty', 'Nur-Sultan', 'Shymkent', 'Aktobe', 'Taraz', 'Pavlodar', 'Ust-Kamenogorsk', 'Karaganda', 'Semey'],
  LA: ['Vientiane', 'Savannakhet', 'Pakse', 'Luang Prabang', 'Thakhek', 'Xam Neua', 'Muang Xay', 'Phonsavan'],
  LB: ['Beirut', 'Tripoli', 'Sidon', 'Tyre', 'Nabatieh', 'Jounieh', 'Zahle', 'Baalbek', 'Byblos', 'Aley'],
  LC: ['Castries', 'Bisee', 'Vieux Fort', 'Micoud', 'Soufrière', 'Dennery', 'Gros Islet'],
  LI: ['Vaduz', 'Schaan', 'Balzers', 'Triesen', 'Eschen', 'Mauren', 'Triesenberg'],
  LK: ['Colombo', 'Dehiwala-Mount Lavinia', 'Moratuwa', 'Sri Jayewardenepura Kotte', 'Negombo', 'Kandy', 'Kalmunai', 'Vavuniya'],
  LR: ['Monrovia', 'Gbarnga', 'Kakata', 'Bensonville', 'Harper', 'Voinjama', 'Zwedru', 'Buchanan'],
  LS: ['Maseru', 'Teyateyaneng', 'Mafeteng', 'Hlotse', 'Mohale\'s Hoek', 'Maputsoe', 'Qacha\'s Nek'],
  LT: ['Vilnius', 'Kaunas', 'Klaipėda', 'Šiauliai', 'Panevėžys', 'Alytus', 'Marijampolė', 'Mažeikiai', 'Jonava', 'Utena'],
  LU: ['Luxembourg City', 'Esch-sur-Alzette', 'Differdange', 'Dudelange', 'Ettelbruck', 'Diekirch', 'Strassen'],
  LV: ['Riga', 'Daugavpils', 'Liepāja', 'Jelgava', 'Jūrmala', 'Ventspils', 'Rēzekne', 'Valmiera', 'Jēkabpils', 'Ogre'],
  LY: ['Tripoli', 'Benghazi', 'Misrata', 'Tarhuna', 'Al Khums', 'Az Zawiyah', 'Ajdabiya', 'Tobruk', 'Sabha'],
  MA: ['Rabat', 'Casablanca', 'Marrakech', 'Fez', 'Tangier', 'Agadir', 'Meknes', 'Oujda', 'Kenitra', 'Tetouan'],
  MC: ['Monaco', 'Monte Carlo', 'La Condamine', 'Fontvieille'],
  MD: ['Chișinău', 'Tiraspol', 'Bălți', 'Bender', 'Rîbnița', 'Cahul', 'Ungheni', 'Soroca', 'Orhei', 'Comrat'],
  ME: ['Podgorica', 'Nikšić', 'Pljevlja', 'Bijelo Polje', 'Cetinje', 'Bar', 'Herceg Novi', 'Berane', 'Budva'],
  MF: ['Marigot', 'Grand Case', 'Quartier d\'Orléans'],
  MG: ['Antananarivo', 'Toamasina', 'Antsirabe', 'Fianarantsoa', 'Mahajanga', 'Toliara', 'Antsiranana', 'Ambovombe'],
  MH: ['Majuro', 'Ebeye', 'Arno', 'Jabor', 'Wotje', 'Mili'],
  MK: ['Skopje', 'Bitola', 'Kumanovo', 'Prilep', 'Tetovo', 'Veles', 'Štip', 'Ohrid', 'Gostivar', 'Strumica'],
  ML: ['Bamako', 'Sikasso', 'Mopti', 'Koutiala', 'Ségou', 'Kayes', 'Gao', 'Kati', 'Tombouctou', 'San'],
  MM: ['Yangon', 'Mandalay', 'Naypyidaw', 'Mawlamyine', 'Bago', 'Pathein', 'Monywa', 'Meiktila', 'Myitkyina'],
  MN: ['Ulaanbaatar', 'Erdenet', 'Darkhan', 'Choibalsan', 'Murun', 'Bayankhongor', 'Olgiy', 'Hovd', 'Arvayheer'],
  MO: ['Macao'],
  MP: ['Saipan', 'Tinian', 'Rota'],
  MQ: ['Fort-de-France', 'Le Lamentin', 'Le Robert', 'Sainte-Marie', 'Le François', 'Ducos'],
  MR: ['Nouakchott', 'Nouadhibou', 'Néma', 'Kaédi', 'Rosso', 'Zouérat', 'Atar', 'Selibaby'],
  MS: ['Plymouth', 'Brades'],
  MT: ['Valletta', 'Birkirkara', 'Mosta', 'Qormi', 'Żabbar', 'St. Paul\'s Bay', 'San Ġwann', 'Naxxar'],
  MU: ['Port Louis', 'Beau Bassin-Rose Hill', 'Vacoas-Phoenix', 'Curepipe', 'Quatre Bornes', 'Triolet'],
  MV: ['Malé', 'Addu City', 'Fuvahmulah', 'Kulhudhuffushi', 'Thinadhoo', 'Ungoofaaru'],
  MW: ['Lilongwe', 'Blantyre', 'Mzuzu', 'Zomba', 'Kasungu', 'Mangochi', 'Karonga', 'Salima', 'Liwonde'],
  MX: ['Mexico City', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana', 'León', 'Juárez', 'Torreón', 'Querétaro', 'San Luis Potosí'],
  MY: ['Kuala Lumpur', 'George Town', 'Ipoh', 'Shah Alam', 'Petaling Jaya', 'Johor Bahru', 'Seremban', 'Kuala Terengganu'],
  MZ: ['Maputo', 'Matola', 'Nampula', 'Beira', 'Chimoio', 'Nacala', 'Quelimane', 'Tete', 'Xai-Xai', 'Lichinga'],
  NA: ['Windhoek', 'Rundu', 'Walvis Bay', 'Swakopmund', 'Oshakati', 'Rehoboth', 'Katima Mulilo', 'Otjiwarongo'],
  NC: ['Nouméa', 'Mont-Dore', 'Dumbéa', 'Païta', 'Wé', 'Lifou', 'Koné', 'Voh'],
  NE: ['Niamey', 'Zinder', 'Maradi', 'Agadez', 'Tahoua', 'Dosso', 'Arlit', 'Tillabéri', 'Diffa'],
  NF: ['Kingston', 'Burnt Pine'],
  NG: ['Lagos', 'Kano', 'Ibadan', 'Abuja', 'Port Harcourt', 'Benin City', 'Maiduguri', 'Zaria', 'Aba', 'Jos'],
  NI: ['Managua', 'León', 'Masaya', 'Matagalpa', 'Chinandega', 'Granada', 'Jinotega', 'Estelí', 'Corinto'],
  NL: ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven', 'Tilburg', 'Groningen', 'Almere', 'Breda', 'Nijmegen'],
  NO: ['Oslo', 'Bergen', 'Stavanger', 'Trondheim', 'Fredrikstad', 'Kristiansand', 'Sandnes', 'Tromsø', 'Sarpsborg', 'Skien'],
  NP: ['Kathmandu', 'Pokhara', 'Lalitpur', 'Bharatpur', 'Biratnagar', 'Birgunj', 'Dharan', 'Bhaktapur', 'Butwal'],
  NR: ['Yaren', 'Denigomodu', 'Meneng', 'Aiwo', 'Anabar', 'Anetan'],
  NU: ['Alofi', 'Hakupu', 'Tuapa', 'Namukulu'],
  NZ: ['Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'Tauranga', 'Napier-Hastings', 'Dunedin', 'Palmerston North'],
  OM: ['Muscat', 'Seeb', 'Salalah', 'Bawshar', 'Sohar', 'As Suwayq', 'Nizwa', 'Sur', 'Bahla'],
  PA: ['Panama City', 'San Miguelito', 'Tocumen', 'David', 'Arraijan', 'Colón', 'La Chorrera', 'Pacora'],
  PE: ['Lima', 'Arequipa', 'Callao', 'Trujillo', 'Chiclayo', 'Iquitos', 'Huancayo', 'Piura', 'Cusco', 'Chimbote'],
  PF: ['Papeete', 'Faaa', 'Punaauia', 'Pirae', 'Moorea', 'Mahina', 'Paea', 'Papao'],
  PG: ['Port Moresby', 'Lae', 'Mount Hagen', 'Popondetta', 'Madang', 'Wewak', 'Vanimo', 'Kimbe'],
  PH: ['Manila', 'Quezon City', 'Caloocan', 'Davao', 'Cebu City', 'Zamboanga', 'Antipolo', 'Pasig', 'Taguig', 'Valenzuela'],
  PK: ['Karachi', 'Lahore', 'Faisalabad', 'Rawalpindi', 'Gujranwala', 'Peshawar', 'Multan', 'Hyderabad', 'Islamabad', 'Quetta'],
  PL: ['Warsaw', 'Kraków', 'Łódź', 'Wrocław', 'Poznań', 'Gdańsk', 'Szczecin', 'Bydgoszcz', 'Lublin', 'Katowice'],
  PM: ['Saint-Pierre', 'Miquelon'],
  PN: ['Adamstown'],
  PR: ['San Juan', 'Bayamón', 'Carolina', 'Ponce', 'Caguas', 'Guaynabo', 'Arecibo', 'Toa Baja'],
  PS: ['Gaza', 'Hebron', 'Nablus', 'Jabalia', 'Rafah', 'Ramallah', 'Khan Yunis', 'Bethlehem'],
  PT: ['Lisbon', 'Porto', 'Amadora', 'Braga', 'Setúbal', 'Coimbra', 'Queluz', 'Funchal', 'Cacém', 'Vila Nova de Gaia'],
  PW: ['Ngerulmud', 'Koror', 'Airai', 'Melekeok'],
  PY: ['Asunción', 'Ciudad del Este', 'San Lorenzo', 'Luque', 'Capiatá', 'Lambaré', 'Fernando de la Mora'],
  QA: ['Doha', 'Al Rayyan', 'Umm Salal', 'Al Khor', 'Al Wakrah', 'Dukhan', 'Mesaieed'],
  RE: ['Saint-Denis', 'Saint-Paul', 'Saint-Pierre', 'Le Tampon', 'Saint-André', 'Saint-Louis'],
  RO: ['Bucharest', 'Cluj-Napoca', 'Timișoara', 'Iași', 'Constanța', 'Craiova', 'Brașov', 'Galați', 'Ploiești', 'Oradea'],
  RS: ['Belgrade', 'Novi Sad', 'Niš', 'Kragujevac', 'Subotica', 'Zrenjanin', 'Pančevo', 'Čačak', 'Novi Pazar', 'Kraljevo'],
  RU: ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg', 'Nizhny Novgorod', 'Kazan', 'Chelyabinsk', 'Omsk', 'Samara', 'Rostov-on-Don'],
  RW: ['Kigali', 'Butare', 'Gitarama', 'Musanze', 'Gisenyi', 'Byumba', 'Cyangugu', 'Kibuye'],
  SA: ['Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Dammam', 'Khobar', 'Tabuk', 'Buraidah', 'Khamis Mushait', 'Hail'],
  SB: ['Honiara', 'Gizo', 'Auki', 'Kirakira', 'Buala', 'Tulagi', 'Lata'],
  SC: ['Victoria', 'Anse Boileau', 'Beau Vallon', 'Cascade', 'English River'],
  SD: ['Khartoum', 'Omdurman', 'Khartoum North', 'Nyala', 'Port Sudan', 'Kassala', 'Al-Obeid', 'Al-Qadarif'],
  SE: ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala', 'Västerås', 'Örebro', 'Linköping', 'Helsingborg', 'Jönköping', 'Norrköping'],
  SG: ['Singapore'],
  SH: ['Jamestown', 'Half Tree Hollow', 'Longwood'],
  SI: ['Ljubljana', 'Maribor', 'Celje', 'Kranj', 'Velenje', 'Koper', 'Novo Mesto', 'Ptuj', 'Trbovlje', 'Kamnik'],
  SJ: ['Longyearbyen', 'Ny-Ålesund', 'Barentsburg'],
  SK: ['Bratislava', 'Košice', 'Prešov', 'Žilina', 'Banská Bystrica', 'Nitra', 'Trnava', 'Trenčín', 'Martin', 'Poprad'],
  SL: ['Freetown', 'Bo', 'Kenema', 'Koidu', 'Makeni', 'Lunsar', 'Port Loko', 'Waterloo'],
  SM: ['San Marino', 'Serravalle', 'Borgo Maggiore', 'Domagnano', 'Fiorentino'],
  SN: ['Dakar', 'Touba', 'Thiès', 'Kaolack', 'Saint-Louis', 'Ziguinchor', 'Kolda', 'Diourbel', 'Tambacounda'],
  SO: ['Mogadishu', 'Hargeisa', 'Bosaso', 'Kismayo', 'Merca', 'Galcaio', 'Beledweyne', 'Baidoa'],
  SR: ['Paramaribo', 'Lelydorp', 'Brokopondo', 'Nieuw Nickerie', 'Moengo', 'Mariënburg', 'Wageningen'],
  SS: ['Juba', 'Wau', 'Malakal', 'Yei', 'Bentiu', 'Bor', 'Yambio', 'Rumbek'],
  ST: ['São Tomé', 'Santo António', 'Neves', 'Santana', 'Guadalupe', 'Pantufo'],
  SV: ['San Salvador', 'Soyapango', 'Santa Ana', 'San Miguel', 'Mejicanos', 'Santa Tecla', 'Apopa'],
  SX: ['Philipsburg', 'Lower Prince\'s Quarter', 'Cul de Sac', 'Simpson Bay'],
  SY: ['Damascus', 'Aleppo', 'Homs', 'Latakia', 'Hama', 'Raqqa', 'Deir ez-Zor', 'Hasakah', 'Qamishli', 'Daraa'],
  SZ: ['Mbabane', 'Manzini', 'Big Bend', 'Malkerns', 'Nhlangano', 'Siteki', 'Piggs Peak'],
  TC: ['Cockburn Town', 'Providenciales', 'Five Cays', 'Blue Hills'],
  TD: ['N\'Djamena', 'Moundou', 'Sarh', 'Abéché', 'Kelo', 'Koumra', 'Pala', 'Am Timan'],
  TF: ['Martin-de-Viviès', 'Port-aux-Français'],
  TG: ['Lomé', 'Sokodé', 'Kara', 'Palimé', 'Atakpamé', 'Bassar', 'Tsévié', 'Aného'],
  TH: ['Bangkok', 'Samut Prakan', 'Mueang Nonthaburi', 'Udon Thani', 'Chon Buri', 'Nakhon Ratchasima', 'Chiangmai', 'Hat Yai'],
  TJ: ['Dushanbe', 'Khujand', 'Kulob', 'Bokhtar', 'Istaravshan', 'Kanibadam', 'Isfara', 'Panjakent'],
  TK: ['Atafu', 'Nukunonu', 'Fakaofo'],
  TL: ['Dili', 'Dare', 'Baucau', 'Maliana', 'Suai', 'Same', 'Liquiçá', 'Aileu'],
  TM: ['Ashgabat', 'Turkmenbashi', 'Dashoguz', 'Mary', 'Balkanabat', 'Bayramaly', 'Türkmenabat', 'Tejen'],
  TN: ['Tunis', 'Sfax', 'Sousse', 'Ettadhamen', 'Kairouan', 'Gabès', 'Bizerte', 'Ariana', 'Gafsa', 'El Mourouj'],
  TO: ['Nuku\'alofa', 'Mu\'a', 'Vaini', 'Pangai', 'Neiafu', 'Haveluloto'],
  TR: ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Adana', 'Gaziantep', 'Konya', 'Çankaya', 'Antalya', 'Bağcılar'],
  TT: ['Port of Spain', 'San Fernando', 'Chaguanas', 'Arima', 'Point Fortin', 'Laventille', 'Princes Town'],
  TV: ['Funafuti', 'Asau', 'Lolua', 'Savave', 'Tanrake', 'Toga'],
  TW: ['Taipei', 'Kaohsiung', 'Taichung', 'Tainan', 'Taoyuan', 'Hsinchu', 'Keelung', 'Chiayi'],
  TZ: ['Dar es Salaam', 'Mwanza', 'Arusha', 'Dodoma', 'Mbeya', 'Morogoro', 'Tanga', 'Kahama', 'Tabora', 'Zanzibar City'],
  UA: ['Kiev', 'Kharkiv', 'Odessa', 'Dnipro', 'Donetsk', 'Zaporizhzhia', 'Lviv', 'Kryvyi Rih', 'Mykolaiv', 'Mariupol'],
  UG: ['Kampala', 'Gulu', 'Lira', 'Mbarara', 'Jinja', 'Bwizibwera', 'Mbale', 'Mukono', 'Kasese', 'Masaka'],
  UM: ['Wake Island', 'Johnston Atoll', 'Midway Atoll'],
  US: ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose'],
  UY: ['Montevideo', 'Salto', 'Paysandú', 'Las Piedras', 'Rivera', 'Maldonado', 'Tacuarembó', 'Melo', 'Mercedes', 'Artigas'],
  UZ: ['Tashkent', 'Namangan', 'Samarkand', 'Andijan', 'Nukus', 'Bukhara', 'Qarshi', 'Kokand', 'Margilan', 'Fergana'],
  VA: ['Vatican City'],
  VC: ['Kingstown', 'Georgetown', 'Barrouallie', 'Port Elizabeth', 'Layou', 'Calliaqua'],
  VE: ['Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto', 'Maracay', 'Ciudad Guayana', 'San Cristóbal', 'Maturín'],
  VG: ['Road Town', 'Spanish Town', 'The Settlement', 'East End', 'Long Look'],
  VI: ['Charlotte Amalie', 'Christiansted', 'Frederiksted', 'Cruz Bay', 'Coral Bay'],
  VN: ['Ho Chi Minh City', 'Hanoi', 'Haiphong', 'Da Nang', 'Bien Hoa', 'Hue', 'Nha Trang', 'Can Tho', 'Rach Gia'],
  VU: ['Port Vila', 'Luganville', 'Norsup', 'Sola', 'Lenakel', 'Isangel', 'Saratamata'],
  WF: ['Mata Utu', 'Leava', 'Alo'],
  WS: ['Apia', 'Asau', 'Mulifanua', 'Safotulafai', 'Leulumoega', 'Siusega'],
  YE: ['Sanaa', 'Aden', 'Taiz', 'Al Hudaydah', 'Mukalla', 'Ibb', 'Dhamar', 'Amran', 'Saada'],
  YT: ['Mamoudzou', 'Koungou', 'Dzaoudzi', 'Dembeni', 'Bandrele', 'Pamandzi'],
  ZA: ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria', 'Port Elizabeth', 'Bloemfontein', 'East London', 'Nelspruit', 'Kimberley', 'Polokwane'],
  ZM: ['Lusaka', 'Kitwe', 'Ndola', 'Kabwe', 'Chingola', 'Mufulira', 'Livingstone', 'Luanshya', 'Kasama', 'Chipata'],
  ZW: ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare', 'Epworth', 'Gweru', 'Kwekwe', 'Kadoma', 'Masvingo', 'Chinhoyi'],
};

// Helper functions
export const getCountryByCode = (code: string): Country | undefined => {
  return countries.find(country => country.code === code);
};

export const getCountryByName = (name: string): Country | undefined => {
  return countries.find(country => country.name === name);
};

export const getCitiesByCountryCode = (code: string): string[] => {
  return cities[code] || [];
};

export const getCitiesByCountryName = (countryName: string): string[] => {
  const country = getCountryByName(countryName);
  return country ? getCitiesByCountryCode(country.code) : [];
};

export const searchCountries = (query: string): Country[] => {
  if (!query) return countries;
  
  const lowerQuery = query.toLowerCase();
  return countries.filter(country => 
    country.name.toLowerCase().includes(lowerQuery) ||
    country.code.toLowerCase().includes(lowerQuery)
  );
};

export const searchCities = (query: string, countryCode?: string): string[] => {
  if (!query) return countryCode ? getCitiesByCountryCode(countryCode) : [];
  
  const lowerQuery = query.toLowerCase();
  const targetCities = countryCode ? getCitiesByCountryCode(countryCode) : 
    Object.values(cities).flat();
  
  return targetCities.filter(city => 
    city.toLowerCase().includes(lowerQuery)
  );
};

export default {
  countries,
  cities,
  getCountryByCode,
  getCountryByName,
  getCitiesByCountryCode,
  getCitiesByCountryName,
  searchCountries,
  searchCities,
};